spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: '{cipher}AYB6BeXZ3dFuECNG49TK+5yYoqoF2yxe/957eBN5SXmX7Fq1tpwXt4z/M9RAbFbAXpihCLe6i541VfYxVE86fTqji0OE1Nf778jPk1mH6Cp7oHgaZEVkdXQt4y2REAyeMPJ5X+P/DQ2Oy8AA2ur+a+aRZTA676gHKb5SF+Kf26C9Qk9M5+Gq7k3AU5hytUpN1q2+jWp3blqSGXfwdWYEK1nnGA1BDuf0IN/cYX6f/ZyOIvs4KvAfS3/0zu/5mYXihED+6stecCR22gv3unA88nKGNAv0kB+Brq7Qa8eMc+5ORE/K8e5yH0tarfERecNCj6W/SgdzJUOoRo942KJRv5VL6JVh0GvbaN2bU2JT7BuaveTR0L1p3UHTuoRMBhnU0Ufb9WZQVNkT+qBYQKNMUBLEeWnSVVVmvzwFyw6XOg3INUVnq9DOCh2rB4hUcDA4K8MvnHjafZrdzxQxA8EdsOLdbiMbzmlGNEIhjwZuMWwKs7bp8cS4Y7XhH90BNbXqu3q7Keu69V3ZoMZJohlUObgJ0Wjop2B+Mpg37TqHiy8Jkg=='

token:
  expiration_time: 86400000
  secret: '{cipher}AYAH2VuE4+yrawTqudDqdmPbxRgNM8QPhVwZRdkKinz4oYd8GmWgdeOj+KDtAp1DvjswPgoPhLdnber+o+j0OjRiZ1HCMHuVQz7ifTUav+PrM/FCwTgiqhfLG6DfuDYiJiB/pzqSGUPv2gdy4+bdErjCAPlUuo5yDv43+m/SwKuucqgvWY58nHPxEx4wnuhNGaX7as+kk1jefpki6HVG971BDBUaRfYwM0LeMRzOK+hU+crjU4wibxL8aIR9VqN9W0tulEGv/ksTVakzoG+5Wvquo+QbhI+6mrKlIHRcVOteqUL6GL4ljuzzG8+J0wo/Fm9+KVTopvVuY4fmVEGAXL4pKqOH53DWCZgEYlC5pqXv/vinXipBNondL0G+1NvXkFZO2c3EHtQ+keEwNG90rpnj7fFKYNrQKFM5DoVJZQffkmsxNIGMCvUNMi+isem7ynL+02b8Pp0ftgLYVl44NatLtVomFdqgNQXMNu7KT/jKqjqFMOWNVx72dmg3r/rBCjMxCpnJdbr9/ZvKEAlRc4Dqb4gmbXDR7ziDxSyAksGuHupQx2KX/MBexu0qMAhhdCA='

gateway:
  ip: 192.168.11.9

order_service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  # http://ORDER-SERVICE -> load balancer
  exception:
    orders_is_empty: User's orders is empty.
